package key

const (
	CHAR_NAME_STR = "Strenght"
	CHAR_NAME_DEX = "Dexterity"
	CHAR_NAME_END = "Endurance"
	CHAR_NAME_INT = "Intelligence"
	CHAR_NAME_EDU = "Education"
	CHAR_NAME_SOC = "Social Standing"
	CHAR_NAME_WLT = "Wealth"
	CHAR_NAME_LCK = "Luck"
	CHAR_NAME_MRL = "Morale"
	CHAR_NAME_STY = "Sanity"
	CHAR_NAME_PSY = "Psionics"
	CHAR_NAME_INS = "Instinct"
	CHAR_NAME_PCK = "Pack"
	CHAR_NAME_TER = "Territory"
	CHAR_NAME_CHA = "Charisma"
	CHAR_CODE_C1  = "C1"
	CHAR_CODE_C2  = "C2"
	CHAR_CODE_C3  = "C3"
	CHAR_CODE_C4  = "C4"
	CHAR_CODE_C5  = "C5"
	CHAR_CODE_C6  = "C6"
	CHAR_CODE_CS  = "CS"
	CHAR_CODE_CP  = "CP"
	CHAR_CODE_CM  = "CM"
	CHAR_CODE_CW  = "CW"
	CHAR_CODE_CL  = "CL"
	CHAR_CODE_CO  = "CO"
)
